[package]
name = "pq-falcon-sigs"
version = "0.0.0"
authors = ["chiefbiiko <noah.anabiik.schwarz@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.42"
atty = "0.2.14"
clap = "3.0.0-beta.2"
home = "0.5.3"
pqcrypto = "0.14.0"
pqcrypto-falcon = "0.2.5"
pqcrypto-traits = "0.3.3"